name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: run
      env:
        MY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ..
        git clone https://github.com/dotabap/dotabap-validator.git
        git clone https://github.com/dotabap/dotabap-generated.git
        cd dotabap-validator
        npm install
        npm ls
        cd ..
        dotabap-validator/generate dotabap-list/list.json $MY_TOKEN > dotabap-generated/generated.json
    - name: dotabap/dotabap-generated
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        deploy_key: ${{ secrets.DEPLOY_DOTABAP_GENERATED }}
        external_repository: dotabap/dotabap-generated
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'        
        publish_branch: main
        cname: generated.dotabap.org
        publish_dir: ../dotabap-generated
